### ISSUE TITLE
Enderite Elytra Chestplate not working

### ISSUE THREAD

**Issue by AbiHerobrineYT** [Nic4Las/Minecraft-Enderite-Mod#10]
Is the Enderite Elytra Chestplate not compatible with the Colytra Mod?
https://www.curseforge.com/minecraft/mc-mods/colytra-fabric

Because I can't use it, or is it broken? It just doesn't deploy. Is it possible to fix or make it compatible with the mods?
All the chestplates with elytra and normal elytra are working fine

**Comment by Pitti11** [comment]
Well as it stands it is not compatible because both implement an elytra recipe. But if you have 2 Elytras it seems to work if you craft an elytra with the Enderite Elytra Chestplate, but it will also look like you have 2 Elytras. Also they implement a different way of activating fall flying which seems to collide with ours.
