### ISSUE TITLE
[Suggestion] Compatibility features with Farmer's Delight

### ISSUE THREAD

**Issue by chemlzh** [Nic4Las/Minecraft-Enderite-Mod#105]
1. I have tested whether the enderite shear can be used to interact with cutting board from [Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight). The result is NO. It cannot cut leather armor into leather. Therefore could you please fix this problem to make enderite shears usable on cutting board like vanilla shears?
2. Farmer's Delight has added knives, which can cut food on cutting board, and attacking mobs with a knife will obtain rare material drops. And some addon mods (like [Delightful)](https://www.curseforge.com/minecraft/mc-mods/delightful) have also introduced knives made of other mod materials. However, the enderite knives in Delightful are not based on your mod, but on [LieOnLion's Enderite](https://www.curseforge.com/minecraft/mc-mods/enderite-lieonlion), and the color doesn't match your mod. So how about brought knife into your mod, which can only be enabled if Farmer's Delight is installed?

**Comment by Pitti11** [comment]
For 1.: Farmer's Delight uses the 'forge:shears' tag, which we forgot. Thank you for bringing it up, it is fixed in: v1.5.1.
A quick fix for older versions would be to use a datapack which adds 'enderitemod:enderite_shears' to the 'forge:shears' tag.
For 2.: We are currently not thinking about adding new weapons, sorry.
