### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by MickeyNotFound** [Nic4Las/Minecraft-Enderite-Mod#121]
Whenever i add this mod to my server i get 

'network protocol error' upon joining the server

In Console: 
[User Authenticator #1/INFO]: UUID of player MickeyNotFound is ecf7497d-8ea8-49fd-bbd1-de7405521949
[18:42:17] [Server thread/INFO]: com.mojang.authlib.GameProfile@210e552e[id=ecf7497d-8ea8-49fd-bbd1-de7405521949,name=MickeyNotFound,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcyNjQxODUzNDc5NiwKICAicHJvZmlsZUlkIiA6ICJlY2Y3NDk3ZDhlYTg0OWZkYmJkMWRlNzQwNTUyMTk0OSIsCiAgInByb2ZpbGVOYW1lIiA6ICJNaWNrZXlOb3RGb3VuZCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAia
HR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83MzMzOWYxN2NlMmI2YWEyM2IzZDk0ZGNkM2UxNjA2YjcxYzVhMGRkOTQ2OWY1NDE4NjRmZWMzNGM5NGY4NDk5IgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMzQwYzBlMDNkZDI0YTExYjE1YThiMzNjMmE3ZTllMzJhYmIyMDUxYjI0ODFkMGJhN2RlZmQ2MzVjYTdhOTMzIgogICAgfQogIH0KfQ==, signature=PDSYy+DjekcrC7Vhfq4bnxIYUHCdhNkgzSyxDoCI31LkE+EAKIkdsAZapKyoZXO0Ro7JjDh2UlNIjY2pz2WiZh2NOEF7YqIJEUb5vtAj9jZVs5JFk+j+jemNpgb9j6O92pr9ZxoYPrl/0a/HbduUHzLSlkmpZ6/1DgaKvqLzDnbBojElMZsIehKPdmkaTGN3t57WGn5bn2CJrY6xKa7WeMSLKxkSy40l6bjmDX/XvH5QxFwO5rnEGs7iKMRJx75faNKQydceih6SBGKQ3uXxoZtf/X0yFwOkif4xHfje70yDKRpEElNlSOHmSlUlUOyihQwsElbB0tQcgSzmDBVOUOu8EVL6AEzx3XqE5+KFcrMFqToiU14uCplIw2tix0OpnwV2Zk0c08Ev0QzdimQ5umdd7H7O2V585qtF+2BLiI7ApinkhpUYkBR5zXS0xlxKX1wGJmRSCtiye5NoiZCFM7iMGpIIb76tNRoZ8CxlDoqDOjGcLjKtFnuYt80eJ6muZT9KPAvIETVw1obER2rBt5kelXJQsau6f1IAh9bl4/tMKQDgglWU88CE/1AQ36Q3KaP1/yhrfblQdU0SauF1ovL4lvZQ8woc3pRCkfS1QnvpRbYLR8iJLThEkEuvFEg2FyX0dL30UswI0rMmRdxpj4kzZrpBvD94wgaBsDuz3yI=]]}] lost connection: Disconnected'' 

[disconnect-2024-09-15_18.42.16-client.txt](https://github.com/user-attachments/files/17006577/disconnect-2024-09-15_18.42.16-client.txt)

**Comment by Nic4Las** [comment]
Looks like a conflict between Optifine and Fabric. Optifine is messing with minecraft internals to such an extend that even relatively simple mods like ours can't load. Since you are on fabric with a nvidia gpu I would recommend you look into nvidium (https://modrinth.com/mod/nvidium). You can expect fps in the hundreds with 32 chunks render distance ez. If nvidium doesn't work or you want shaders use sodium + iris (https://modrinth.com/mod/sodium) and (https://modrinth.com/mod/iris) . That will work almost 100% of the time and is still wayyy better than Optifine. Sadly we can't really do much to support Optifine since it is closed source and we can't even see the name of the Optifine method that crashes.

**Comment by MickeyNotFound** [comment]
Hey,

Thanks for the quisck repsonse.

Even with optifine completely removed i still get the same error
(no other mods have been installed on the server)

**Comment by MickeyNotFound** [comment]
I noticed it does work when i install the mod clientside aswell asserverside

**Comment by Nic4Las** [comment]
Yes that's sadly unavoidable. We need the client to register custom renderer and the like. For most normal mods you always need mods on both server and client.
